apiVersion: v1
kind: Secret
metadata:
  name: counter-database
type: Opaque
data:
  database-host: Y291bnRlci1kYXRhYmFzZQ==
  database-name: Y291bnRlcg==
  database-user: Y291bnRlcg==
  database-password: Y291bnRlcg==